#!/usr/bin/env bash
# Regenerate chapters-data.js from all chapters/*/diagrams/graph/*.json files.
# Run from anywhere; uses absolute paths.
set -e

ROOT="/Users/theusual_pro/Documents/claude-code/systems-intelligence"
OUT="$ROOT/_meta/viewer/chapters-data.js"

python3 - <<'PY' > "$OUT"
import json, os, re, glob

ROOT = "/Users/theusual_pro/Documents/claude-code/systems-intelligence"
chapters = []

# Order: front-matter/* then ch01..ch09 then chX then back-matter/*
chapter_paths = []
# front matter: preface, prologue, acknowledgments, etc.
fm_root = f"{ROOT}/chapters/front-matter"
if os.path.isdir(fm_root):
    for sub in sorted(os.listdir(fm_root)):
        p = f"front-matter/{sub}"
        if os.path.isdir(f"{ROOT}/chapters/{p}"):
            chapter_paths.append(p)
# numbered chapters
chapter_paths.extend(sorted([d for d in os.listdir(f"{ROOT}/chapters") if d.startswith("ch") and d != "chX"]))
chapter_paths.append("chX")
# back matter
bm_root = f"{ROOT}/chapters/back-matter"
if os.path.isdir(bm_root):
    for sub in sorted(os.listdir(bm_root)):
        p = f"back-matter/{sub}"
        if os.path.isdir(f"{ROOT}/chapters/{p}"):
            chapter_paths.append(p)

entries = []
for ch in chapter_paths:
    graph_dir = f"{ROOT}/chapters/{ch}/diagrams/graph"
    if not os.path.isdir(graph_dir):
        continue
    files = sorted(glob.glob(f"{graph_dir}/*.json"))
    for f in files:
        try:
            with open(f) as fh:
                data = json.load(fh)
        except Exception as e:
            print(f"// SKIP {f}: {e}", flush=True)
            continue
        # Pretty chapter label: ch01 -> Ch01, chX -> ChX, front-matter/preface -> Preface, back-matter/appendix-a -> Appendix A
        if ch.startswith("front-matter/") or ch.startswith("back-matter/"):
            sub = ch.split("/", 1)[1]
            ch_label = " ".join(w.capitalize() for w in sub.replace("-", " ").split())
        elif ch == "chX":
            ch_label = "ChX"
        else:
            ch_label = "Ch" + ch[2:].zfill(2)
        # Diagram number from filename or id
        m = re.search(r"(\d+)", os.path.basename(f))
        num = m.group(1) if m else "?"
        title = data.get("title", data.get("id", os.path.basename(f)))
        node_count = len(data.get("nodes", []))
        latent_count = sum(1 for n in data.get("nodes", []) if n.get("is_latent"))
        suffix = f"[{node_count}" + (f", {latent_count} latent" if latent_count else "") + "]"
        label = f"{ch_label} · {num} — {title} {suffix}"
        entries.append({"label": label, "data": data})

print("// AUTO-GENERATED by build-data.sh — do not edit by hand")
print("// Run: bash _meta/viewer/build-data.sh")
print(f"// Total diagrams: {len(entries)}")
print("window.__DIAGRAMS__ = " + json.dumps(entries, indent=2, ensure_ascii=False) + ";")
PY

echo "Wrote $OUT" >&2
wc -l "$OUT" >&2
